FROM python:3.6-slim

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
    git-core \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY requirements.txt requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY . .

# run server
CMD ["./entrypoint.sh"]
